import { NextRequest, NextResponse } from 'next/server';
import { GoogleGenAI } from '@google/genai';
import { auth } from '@/app/lib/firebase/adminConfig';
import { readConversationFile, updateConversationFile } from '@/app/lib/markdown';

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY || '',
});

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    
    // Verify authentication
    const authHeader = request.headers.get('Authorization');
    if (!authHeader?.startsWith('Bearer ')) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const token = authHeader.split('Bearer ')[1];
    const decodedToken = await auth.verifyIdToken(token);
    const userId = decodedToken.uid;

    // Read the conversation file
    const conversation = await readConversationFile(userId, id);
    if (!conversation) {
      return NextResponse.json({ error: 'Conversation not found' }, { status: 404 });
    }

    // Extract dialogue content
    const dialogueContent = conversation.content.split('## Summary')[0].trim();

    // Generate summary using Gemini with consistent markdown template
    const prompt = `You are a conversation analyst. Generate a comprehensive summary of this conversation in the EXACT markdown format specified below.

FULL TRANSCRIPT: "${dialogueContent}"

Generate a summary using this EXACT markdown template:

# Conversation Summary

## 📊 Overview
- **Duration**: [estimate based on content length]
- **Date**: [use current date]
- **Transcript Length**: [number of words]

## 💬 Key Topics Discussed
[Bullet points of 3-5 main topics that were discussed. If no speech, write "No topics - conversation not captured"]

## 😊 Emotional Journey
[Describe the emotional progression throughout the conversation. Include specific emotions detected and any notable shifts. If no emotions detected, write "Emotions not captured"]

## ✨ Highlights & Key Moments
[Bullet points of 2-4 notable moments, insights, or turning points in the conversation. If minimal content, write "Not enough data captured"]

## 💡 Insights & Patterns
[2-3 sentences analyzing communication patterns, emotional intelligence, or conversation dynamics observed]

## 🎯 Recommendations for Next Time
[Bullet points with 2-3 actionable suggestions for improving future conversations based on what was observed]

---
*Generated by SpeakEasy Conversation Coach*

IMPORTANT:
- Follow the template EXACTLY as shown above
- Use the same headers, emoji, and structure
- Keep it concise but insightful
- Be specific to the actual conversation content
- If data is limited, acknowledge it but still provide the template structure`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    const summary = response.text;

    // Update the conversation file with the new summary
    await updateConversationFile(userId, id, { summary });

    return NextResponse.json({ 
      success: true, 
      summary 
    });

  } catch (error) {
    console.error('Error generating summary:', error);
    return NextResponse.json(
      { error: 'Failed to generate summary' },
      { status: 500 }
    );
  }
}
